// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/getcihub/cihub/core (interfaces: JobStore,RunnerStore,Scheduler,Session,UserService,UserStore)
//
// Generated by this command:
//
//	mockgen -package=mock -destination=mock_gen.go github.com/getcihub/cihub/core JobStore,RunnerStore,Scheduler,Session,UserService,UserStore
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	http "net/http"
	reflect "reflect"

	core "github.com/getcihub/cihub/core"
	gomock "go.uber.org/mock/gomock"
)

// MockJobStore is a mock of JobStore interface.
type MockJobStore struct {
	ctrl     *gomock.Controller
	recorder *MockJobStoreMockRecorder
	isgomock struct{}
}

// MockJobStoreMockRecorder is the mock recorder for MockJobStore.
type MockJobStoreMockRecorder struct {
	mock *MockJobStore
}

// NewMockJobStore creates a new mock instance.
func NewMockJobStore(ctrl *gomock.Controller) *MockJobStore {
	mock := &MockJobStore{ctrl: ctrl}
	mock.recorder = &MockJobStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobStore) EXPECT() *MockJobStoreMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockJobStore) Count(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockJobStoreMockRecorder) Count(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockJobStore)(nil).Count), arg0)
}

// Create mocks base method.
func (m *MockJobStore) Create(ctx context.Context, job *core.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockJobStoreMockRecorder) Create(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJobStore)(nil).Create), ctx, job)
}

// Delete mocks base method.
func (m *MockJobStore) Delete(ctx context.Context, job *core.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockJobStoreMockRecorder) Delete(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockJobStore)(nil).Delete), ctx, job)
}

// Find mocks base method.
func (m *MockJobStore) Find(ctx context.Context, owner string, id int64) (*core.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, owner, id)
	ret0, _ := ret[0].(*core.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockJobStoreMockRecorder) Find(ctx, owner, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockJobStore)(nil).Find), ctx, owner, id)
}

// ListCompleted mocks base method.
func (m *MockJobStore) ListCompleted(ctx context.Context, owner string, limit, offset int) ([]*core.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCompleted", ctx, owner, limit, offset)
	ret0, _ := ret[0].([]*core.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCompleted indicates an expected call of ListCompleted.
func (mr *MockJobStoreMockRecorder) ListCompleted(ctx, owner, limit, offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCompleted", reflect.TypeOf((*MockJobStore)(nil).ListCompleted), ctx, owner, limit, offset)
}

// ListIncomplete mocks base method.
func (m *MockJobStore) ListIncomplete(ctx context.Context, owner string) ([]*core.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIncomplete", ctx, owner)
	ret0, _ := ret[0].([]*core.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIncomplete indicates an expected call of ListIncomplete.
func (mr *MockJobStoreMockRecorder) ListIncomplete(ctx, owner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIncomplete", reflect.TypeOf((*MockJobStore)(nil).ListIncomplete), ctx, owner)
}

// Purge mocks base method.
func (m *MockJobStore) Purge(ctx context.Context, before int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Purge", ctx, before)
	ret0, _ := ret[0].(error)
	return ret0
}

// Purge indicates an expected call of Purge.
func (mr *MockJobStoreMockRecorder) Purge(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Purge", reflect.TypeOf((*MockJobStore)(nil).Purge), ctx, before)
}

// Update mocks base method.
func (m *MockJobStore) Update(ctx context.Context, job *core.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, job)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockJobStoreMockRecorder) Update(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockJobStore)(nil).Update), ctx, job)
}

// MockRunnerStore is a mock of RunnerStore interface.
type MockRunnerStore struct {
	ctrl     *gomock.Controller
	recorder *MockRunnerStoreMockRecorder
	isgomock struct{}
}

// MockRunnerStoreMockRecorder is the mock recorder for MockRunnerStore.
type MockRunnerStoreMockRecorder struct {
	mock *MockRunnerStore
}

// NewMockRunnerStore creates a new mock instance.
func NewMockRunnerStore(ctrl *gomock.Controller) *MockRunnerStore {
	mock := &MockRunnerStore{ctrl: ctrl}
	mock.recorder = &MockRunnerStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunnerStore) EXPECT() *MockRunnerStoreMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockRunnerStore) Create(ctx context.Context, runner *core.Runner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, runner)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRunnerStoreMockRecorder) Create(ctx, runner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRunnerStore)(nil).Create), ctx, runner)
}

// Delete mocks base method.
func (m *MockRunnerStore) Delete(ctx context.Context, runner *core.Runner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, runner)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRunnerStoreMockRecorder) Delete(ctx, runner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRunnerStore)(nil).Delete), ctx, runner)
}

// Find mocks base method.
func (m *MockRunnerStore) Find(ctx context.Context, name string) (*core.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, name)
	ret0, _ := ret[0].(*core.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRunnerStoreMockRecorder) Find(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRunnerStore)(nil).Find), ctx, name)
}

// FindID mocks base method.
func (m *MockRunnerStore) FindID(ctx context.Context, id int64) (*core.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindID", ctx, id)
	ret0, _ := ret[0].(*core.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindID indicates an expected call of FindID.
func (mr *MockRunnerStoreMockRecorder) FindID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindID", reflect.TypeOf((*MockRunnerStore)(nil).FindID), ctx, id)
}

// ListIdle mocks base method.
func (m *MockRunnerStore) ListIdle(arg0 context.Context) ([]*core.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIdle", arg0)
	ret0, _ := ret[0].([]*core.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIdle indicates an expected call of ListIdle.
func (mr *MockRunnerStoreMockRecorder) ListIdle(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIdle", reflect.TypeOf((*MockRunnerStore)(nil).ListIdle), arg0)
}

// ListPending mocks base method.
func (m *MockRunnerStore) ListPending(arg0 context.Context) ([]*core.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPending", arg0)
	ret0, _ := ret[0].([]*core.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPending indicates an expected call of ListPending.
func (mr *MockRunnerStoreMockRecorder) ListPending(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPending", reflect.TypeOf((*MockRunnerStore)(nil).ListPending), arg0)
}

// Purge mocks base method.
func (m *MockRunnerStore) Purge(ctx context.Context, before int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Purge", ctx, before)
	ret0, _ := ret[0].(error)
	return ret0
}

// Purge indicates an expected call of Purge.
func (mr *MockRunnerStoreMockRecorder) Purge(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Purge", reflect.TypeOf((*MockRunnerStore)(nil).Purge), ctx, before)
}

// Update mocks base method.
func (m *MockRunnerStore) Update(ctx context.Context, runner *core.Runner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, runner)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRunnerStoreMockRecorder) Update(ctx, runner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRunnerStore)(nil).Update), ctx, runner)
}

// MockScheduler is a mock of Scheduler interface.
type MockScheduler struct {
	ctrl     *gomock.Controller
	recorder *MockSchedulerMockRecorder
	isgomock struct{}
}

// MockSchedulerMockRecorder is the mock recorder for MockScheduler.
type MockSchedulerMockRecorder struct {
	mock *MockScheduler
}

// NewMockScheduler creates a new mock instance.
func NewMockScheduler(ctrl *gomock.Controller) *MockScheduler {
	mock := &MockScheduler{ctrl: ctrl}
	mock.recorder = &MockSchedulerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScheduler) EXPECT() *MockSchedulerMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockScheduler) Cancel(ctx context.Context, runnerName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, runnerName)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cancel indicates an expected call of Cancel.
func (mr *MockSchedulerMockRecorder) Cancel(ctx, runnerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockScheduler)(nil).Cancel), ctx, runnerName)
}

// Cancelled mocks base method.
func (m *MockScheduler) Cancelled(ctx context.Context, runnerName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancelled", ctx, runnerName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cancelled indicates an expected call of Cancelled.
func (mr *MockSchedulerMockRecorder) Cancelled(ctx, runnerName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancelled", reflect.TypeOf((*MockScheduler)(nil).Cancelled), ctx, runnerName)
}

// Request mocks base method.
func (m *MockScheduler) Request(ctx context.Context, params *core.Filter) (*core.Runner, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Request", ctx, params)
	ret0, _ := ret[0].(*core.Runner)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Request indicates an expected call of Request.
func (mr *MockSchedulerMockRecorder) Request(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Request", reflect.TypeOf((*MockScheduler)(nil).Request), ctx, params)
}

// Schedule mocks base method.
func (m *MockScheduler) Schedule(ctx context.Context, runner *core.Runner) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Schedule", ctx, runner)
	ret0, _ := ret[0].(error)
	return ret0
}

// Schedule indicates an expected call of Schedule.
func (mr *MockSchedulerMockRecorder) Schedule(ctx, runner any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Schedule", reflect.TypeOf((*MockScheduler)(nil).Schedule), ctx, runner)
}

// MockSession is a mock of Session interface.
type MockSession struct {
	ctrl     *gomock.Controller
	recorder *MockSessionMockRecorder
	isgomock struct{}
}

// MockSessionMockRecorder is the mock recorder for MockSession.
type MockSessionMockRecorder struct {
	mock *MockSession
}

// NewMockSession creates a new mock instance.
func NewMockSession(ctrl *gomock.Controller) *MockSession {
	mock := &MockSession{ctrl: ctrl}
	mock.recorder = &MockSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSession) EXPECT() *MockSessionMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSession) Create(arg0 http.ResponseWriter, arg1 *core.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSession)(nil).Create), arg0, arg1)
}

// Delete mocks base method.
func (m *MockSession) Delete(arg0 http.ResponseWriter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionMockRecorder) Delete(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSession)(nil).Delete), arg0)
}

// Get mocks base method.
func (m *MockSession) Get(arg0 *http.Request) (*core.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(*core.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockSessionMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSession)(nil).Get), arg0)
}

// MockUserService is a mock of UserService interface.
type MockUserService struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceMockRecorder
	isgomock struct{}
}

// MockUserServiceMockRecorder is the mock recorder for MockUserService.
type MockUserServiceMockRecorder struct {
	mock *MockUserService
}

// NewMockUserService creates a new mock instance.
func NewMockUserService(ctrl *gomock.Controller) *MockUserService {
	mock := &MockUserService{ctrl: ctrl}
	mock.recorder = &MockUserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserService) EXPECT() *MockUserServiceMockRecorder {
	return m.recorder
}

// Find mocks base method.
func (m *MockUserService) Find(ctx context.Context, access, refresh string) (*core.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, access, refresh)
	ret0, _ := ret[0].(*core.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockUserServiceMockRecorder) Find(ctx, access, refresh any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserService)(nil).Find), ctx, access, refresh)
}

// FindEmail mocks base method.
func (m *MockUserService) FindEmail(ctx context.Context, user *core.User) (*core.Email, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindEmail", ctx, user)
	ret0, _ := ret[0].(*core.Email)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindEmail indicates an expected call of FindEmail.
func (mr *MockUserServiceMockRecorder) FindEmail(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindEmail", reflect.TypeOf((*MockUserService)(nil).FindEmail), ctx, user)
}

// ListEmail mocks base method.
func (m *MockUserService) ListEmail(ctx context.Context, user *core.User) ([]*core.Email, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEmail", ctx, user)
	ret0, _ := ret[0].([]*core.Email)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEmail indicates an expected call of ListEmail.
func (mr *MockUserServiceMockRecorder) ListEmail(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEmail", reflect.TypeOf((*MockUserService)(nil).ListEmail), ctx, user)
}

// MockUserStore is a mock of UserStore interface.
type MockUserStore struct {
	ctrl     *gomock.Controller
	recorder *MockUserStoreMockRecorder
	isgomock struct{}
}

// MockUserStoreMockRecorder is the mock recorder for MockUserStore.
type MockUserStoreMockRecorder struct {
	mock *MockUserStore
}

// NewMockUserStore creates a new mock instance.
func NewMockUserStore(ctrl *gomock.Controller) *MockUserStore {
	mock := &MockUserStore{ctrl: ctrl}
	mock.recorder = &MockUserStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserStore) EXPECT() *MockUserStoreMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockUserStore) Count(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockUserStoreMockRecorder) Count(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockUserStore)(nil).Count), arg0)
}

// Create mocks base method.
func (m *MockUserStore) Create(ctx context.Context, user *core.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserStoreMockRecorder) Create(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserStore)(nil).Create), ctx, user)
}

// Delete mocks base method.
func (m *MockUserStore) Delete(ctx context.Context, user *core.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUserStoreMockRecorder) Delete(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUserStore)(nil).Delete), ctx, user)
}

// Find mocks base method.
func (m *MockUserStore) Find(ctx context.Context, id int64) (*core.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*core.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockUserStoreMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockUserStore)(nil).Find), ctx, id)
}

// FindLogin mocks base method.
func (m *MockUserStore) FindLogin(ctx context.Context, login string) (*core.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLogin", ctx, login)
	ret0, _ := ret[0].(*core.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLogin indicates an expected call of FindLogin.
func (mr *MockUserStoreMockRecorder) FindLogin(ctx, login any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLogin", reflect.TypeOf((*MockUserStore)(nil).FindLogin), ctx, login)
}

// FindToken mocks base method.
func (m *MockUserStore) FindToken(ctx context.Context, token string) (*core.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindToken", ctx, token)
	ret0, _ := ret[0].(*core.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindToken indicates an expected call of FindToken.
func (mr *MockUserStoreMockRecorder) FindToken(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindToken", reflect.TypeOf((*MockUserStore)(nil).FindToken), ctx, token)
}

// List mocks base method.
func (m *MockUserStore) List(ctx context.Context, params core.UserParams) ([]*core.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]*core.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockUserStoreMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockUserStore)(nil).List), ctx, params)
}

// Update mocks base method.
func (m *MockUserStore) Update(ctx context.Context, user *core.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserStoreMockRecorder) Update(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserStore)(nil).Update), ctx, user)
}
