// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/getcihub/cihub/cmd/cihub-server/config"
	"github.com/getcihub/cihub/handler/api"
	"github.com/getcihub/cihub/handler/web"
	"github.com/getcihub/cihub/orchestrator/manager"
	runner2 "github.com/getcihub/cihub/service/runner"
	"github.com/getcihub/cihub/store/job"
	"github.com/getcihub/cihub/store/runner"
	"github.com/getcihub/cihub/store/user"
)

import (
	_ "github.com/go-sql-driver/mysql"
	_ "github.com/lib/pq"
	_ "modernc.org/sqlite"
)

// Injectors from wire.go:

func InitializeApplication(conf *config.Config) (application, error) {
	db, err := provideDatabase(conf)
	if err != nil {
		return application{}, err
	}
	jobStore := job.New(db)
	encrypter, err := provideEncrypter(conf)
	if err != nil {
		return application{}, err
	}
	runnerStore := runner.New(db, encrypter)
	clientCreator, err := provideClient(conf)
	if err != nil {
		return application{}, err
	}
	runnerService := runner2.New(clientCreator)
	redisDB, err := provideRedisClient(conf)
	if err != nil {
		return application{}, err
	}
	scheduler := provideScheduler(jobStore, redisDB)
	userStore := user.New(db, encrypter)
	runnerManager := manager.New(jobStore, runnerStore, runnerService, scheduler, userStore)
	agent := provideAgent(runnerManager, conf)
	reaper := provideReaper(runnerStore, runnerService, scheduler, conf)
	session, err := provideSession(userStore, conf)
	if err != nil {
		return application{}, err
	}
	server := api.New(session, userStore)
	options := provideServerOptions(conf)
	webServer := web.New(options)
	mainHealthzHandler := provideHealthz()
	v := provideEventHandlers(jobStore, runnerStore, scheduler)
	mainHookHandler := provideHook(conf, v)
	mainPprofHandler := providePprof(conf)
	mux := provideRouter(server, webServer, mainHealthzHandler, mainHookHandler, mainPprofHandler, conf)
	serverServer := provideServer(mux, conf)
	mainApplication := newApplication(agent, reaper, serverServer, userStore)
	return mainApplication, nil
}
