// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/getcihub/cihub/cmd/cihub-server/config"
	"github.com/getcihub/cihub/handler/api"
	"github.com/getcihub/cihub/handler/rpc"
	"github.com/getcihub/cihub/handler/web"
	"github.com/getcihub/cihub/service/installation"
	runner2 "github.com/getcihub/cihub/service/runner"
	"github.com/getcihub/cihub/service/syncer"
	user2 "github.com/getcihub/cihub/service/user"
	"github.com/getcihub/cihub/store/batch"
	"github.com/getcihub/cihub/store/machine"
	"github.com/getcihub/cihub/store/membership"
	"github.com/getcihub/cihub/store/runner"
	"github.com/getcihub/cihub/store/user"
)

import (
	_ "github.com/lib/pq"
	_ "modernc.org/sqlite"
)

// Injectors from wire.go:

func InitializeApplication(conf *config.Config) (application, error) {
	db, err := provideDatabase(conf)
	if err != nil {
		return application{}, err
	}
	encrypter, err := provideEncrypter(conf)
	if err != nil {
		return application{}, err
	}
	runnerStore := runner.New(db, encrypter)
	clientCreator, err := provideClient(conf)
	if err != nil {
		return application{}, err
	}
	runnerService := runner2.New(clientCreator)
	redisDB, err := provideRedisClient(conf)
	if err != nil {
		return application{}, err
	}
	scheduler := provideScheduler(runnerStore, redisDB)
	reaper := provideReaper(runnerStore, runnerService, scheduler, conf)
	installationStore := provideInstallationStore(db)
	userStore := user.New(db, encrypter)
	refresher := provideRefresher(userStore, conf)
	installationService := installation.New(clientCreator, refresher)
	machineStore := machine.New(db)
	membershipStore := membership.New(db)
	session, err := provideSession(userStore, conf)
	if err != nil {
		return application{}, err
	}
	batcher := batch.New(db)
	coreSyncer := syncer.New(batcher, installationService, installationStore, userStore)
	system := provideSystem(conf)
	userService := user2.New(clientCreator, refresher)
	server := api.New(installationStore, installationService, machineStore, membershipStore, runnerStore, scheduler, session, coreSyncer, system, userStore, userService)
	middleware, err := provideLogin(conf)
	if err != nil {
		return application{}, err
	}
	options := provideServerOptions(conf)
	webServer := web.New(middleware, options, session, coreSyncer, userStore, userService)
	mainHealthzHandler := provideHealthz()
	v := provideEventHandlers(installationStore, runnerStore, scheduler)
	mainHookHandler := provideHook(conf, v)
	mainPprofHandler := providePprof(conf)
	rpcServer := rpc.New(machineStore, runnerStore, runnerService, scheduler)
	mux := provideRouter(server, webServer, mainHealthzHandler, mainHookHandler, mainPprofHandler, rpcServer, conf)
	serverServer := provideServer(mux, conf)
	mainApplication := newApplication(reaper, serverServer, userStore)
	return mainApplication, nil
}
