// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/getcihub/cihub/cmd/cihub/server/config"
	"github.com/getcihub/cihub/handler/api"
	"github.com/getcihub/cihub/handler/web"
	"github.com/getcihub/cihub/store/user"
)

import (
	_ "github.com/go-sql-driver/mysql"
	_ "github.com/lib/pq"
	_ "modernc.org/sqlite"
)

// Injectors from wire.go:

func InitializeApplication(conf *config.Config) (application, error) {
	db, err := provideDatabase(conf)
	if err != nil {
		return application{}, err
	}
	encrypter, err := provideEncrypter(conf)
	if err != nil {
		return application{}, err
	}
	userStore := user.New(db, encrypter)
	session, err := provideSession(userStore, conf)
	if err != nil {
		return application{}, err
	}
	server := api.New(session, userStore)
	options := provideServerOptions(conf)
	webServer := web.New(options)
	serverHealthzHandler := provideHealthz()
	serverPprofHandler := providePprof(conf)
	mux := provideRouter(server, webServer, serverHealthzHandler, serverPprofHandler, conf)
	serverServer := provideServer(mux, conf)
	serverApplication := newApplication(serverServer, userStore)
	return serverApplication, nil
}
